package dog.beepboop.velvet.controlServer.models

import com.amazonaws.services.dynamodbv2.datamodeling.*
import kotlinx.serialization.Serializable
import org.springframework.data.annotation.Id
import java.time.Instant
import java.util.Date

@Serializable
@DynamoDBDocument
data class TransactionRepoId(
    @DynamoDBAutoGeneratedKey
    @get:DynamoDBHashKey(attributeName = "transaction_id")
    var transactionId: String?,
    @get:DynamoDBRangeKey(attributeName = "user_id")
    var userId: String = ""
)

@DynamoDBTable(tableName = "transactions")
data class Transaction (
    @DynamoDBAutoGeneratedKey
    @field:DynamoDBHashKey(attributeName = "transaction_id")
    var transactionId: String?,
    @field:DynamoDBRangeKey(attributeName = "user_id")
    var userId: String = "",
    @DynamoDBAttribute(attributeName = "channel_id")
    var channelId: String = "",
    @DynamoDBAttribute(attributeName = "action_id")
    var actionId: String = "",
    @DynamoDBAttribute
    var date: Date = Date.from(Instant.MIN),
    @DynamoDBAttribute(attributeName = "twitch_transaction_id")
    var twitchTransactionId: String?,
    @DynamoDBAttribute
    var bits: Int = 0
) {
    @Id
    private var id: TransactionRepoId? = null
        get() = TransactionRepoId(transactionId,userId)
}
